"""empty message

Revision ID: 01f7b513e481
Revises: 145b6c112848
Create Date: 2016-02-12 01:01:03.443701

"""

# revision identifiers, used by Alembic.
revision = '01f7b513e481'
down_revision = '145b6c112848'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'teams', 'users', ['user_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_column('teams', 'user_id')
    ### end Alembic commands ###
