"""empty message

Revision ID: 046fd0c15c60
Revises: b84ea16b3b7a
Create Date: 2016-02-14 20:11:06.354126

"""

# revision identifiers, used by Alembic.
revision = '046fd0c15c60'
down_revision = 'b84ea16b3b7a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('teams_created_by_fkey', 'teams', type_='foreignkey')
    op.create_foreign_key(None, 'teams', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.create_foreign_key('teams_created_by_fkey', 'teams', 'users', ['created_by'], ['id'])
    ### end Alembic commands ###
