"""empty message

Revision ID: 1ea848940c89
Revises: 1f46a15b9d3c
Create Date: 2016-02-15 15:29:53.004824

"""

# revision identifiers, used by Alembic.
revision = '1ea848940c89'
down_revision = '1f46a15b9d3c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('postcode', sa.String(), nullable=True))
    op.add_column('teams', sa.Column('time', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'time')
    op.drop_column('teams', 'postcode')
    ### end Alembic commands ###
