"""empty message

Revision ID: 386d83aee4eb
Revises: 7f230de7ce1e
Create Date: 2016-02-14 17:06:05.888964

"""

# revision identifiers, used by Alembic.
revision = '386d83aee4eb'
down_revision = '7f230de7ce1e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollments',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('number_players', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'team_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enrollments')
    ### end Alembic commands ###
