"""empty message

Revision ID: 3fb8e11b97de
Revises: 1ea848940c89
Create Date: 2016-02-15 16:21:14.690284

"""

# revision identifiers, used by Alembic.
revision = '3fb8e11b97de'
down_revision = '1ea848940c89'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('pitch_postcode', sa.String(), nullable=True))
    op.drop_column('teams', 'postcode')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('postcode', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('teams', 'pitch_postcode')
    ### end Alembic commands ###
