"""empty message

Revision ID: 7f230de7ce1e
Revises: 7cc6e82b4f5a
Create Date: 2016-02-14 17:01:29.537344

"""

# revision identifiers, used by Alembic.
revision = '7f230de7ce1e'
down_revision = '7cc6e82b4f5a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enrollments', 'id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollments', sa.Column('id', sa.INTEGER(), nullable=False))
    ### end Alembic commands ###
