"""empty message

Revision ID: b84ea16b3b7a
Revises: 386d83aee4eb
Create Date: 2016-02-14 20:07:25.054038

"""

# revision identifiers, used by Alembic.
revision = 'b84ea16b3b7a'
down_revision = '386d83aee4eb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('enrollments_user_id_fkey', 'enrollments', type_='foreignkey')
    op.drop_constraint('enrollments_team_id_fkey', 'enrollments', type_='foreignkey')
    op.create_foreign_key(None, 'enrollments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'enrollments', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.create_foreign_key('enrollments_team_id_fkey', 'enrollments', 'teams', ['team_id'], ['id'])
    op.create_foreign_key('enrollments_user_id_fkey', 'enrollments', 'users', ['user_id'], ['id'])
    ### end Alembic commands ###
