"""empty message

Revision ID: e57ba17fddee
Revises: 78cd5fc12807
Create Date: 2016-02-11 11:25:50.219584

"""

# revision identifiers, used by Alembic.
revision = 'e57ba17fddee'
down_revision = '78cd5fc12807'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    ### end Alembic commands ###
